language:
  elixir

env:
  global:
    - MIX_ENV=test

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4.5
    - otp_release: 19.3
      elixir: 1.4.5

    - otp_release: 19.3
      elixir: 1.5.3
    - otp_release: 20.2
      elixir: 1.5.3

    - otp_release: 19.3
      elixir: 1.6.6
    - otp_release: 20.3
      elixir: 1.6.6

    - otp_release: 20.3
      elixir: 1.7.3
    - otp_release: 21.1
      elixir: 1.7.3

script:
  - mix do deps.compile, compile
  - >
    if [[ "$(echo "${TRAVIS_ELIXIR_VERSION:0:3}>=1.6" | bc)" == "1" ]]; then
      mix format --check-formatted
    fi;
  - mix credo --strict --ignore maxlinelength,cyclomaticcomplexity,todo
  - mix coveralls.travis
